Repository christianhelle/httpgenerator, pull requests merged in 2024-02, with the labels that each got.

#56 Prefix route variables with operation name when generating single file
  src/HttpGenerator.Core/HttpFileGenerator.cs
Labels: enhancement

#57 Add support for loading authorization header from environment variable
  src/HttpGenerator.Core/GeneratorSettings.cs
  src/HttpGenerator.Core/HttpFileGenerator.cs
  src/HttpGenerator/GenerateCommand.cs
  src/HttpGenerator/Settings.cs
Labels: enhancement

#64 Revert "Update actions/upload-artifact action to v4"
  .github/workflows/build.yml
  .github/workflows/codecov.yml
  .github/workflows/release-template.yml
  .github/workflows/template.yml
Labels: dependencies

#66 Update StringExtensions.cs
  src/HttpGenerator.Core/StringExtensions.cs
Labels: bug, enhancement
